version: "3.8"
services:
  kambingku-ai:
    image: bandung:5000/kambingku-ai/ai:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role == worker"
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.kambingku-ai.rule=Host(`kambingku-ai.gaeni.org`)"
        - "traefik.http.routers.kambingku-ai.entrypoints=https"
        - "traefik.http.routers.kambingku-ai.tls=true"
        - "traefik.http.routers.kambingku-ai.tls.certresolver=le"
        - "traefik.http.services.kambingku-ai.loadbalancer.server.port=8501"
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      TAVILYAPI_KEY: "${TAVILYAPI_KEY}"
      GROQAPI_KEY: "${GROQAPI_KEY}"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
