version: '3.8'

services:
  kambingku:
    image: bandung:5000/kambingku-ai/ai:latest1
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_MODEL_NAME: "gpt-4o"
      GROQ_API_KEY: "${GROQ_API_KEY}"
      TAVILY_API_KEY: "${TAVILY_API_KEY}"

    command: streamlit run main.py --server.port=8501 --server.address=0.0.0.0
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.kambingku.rule=Host(`kambingku-ai.gaeni.org`)"
        - "traefik.http.routers.kambingku.entrypoints=websecure"
        - "traefik.http.routers.kambingku.tls=true"
        - "traefik.http.routers.kambingku.tls.certresolver=le"
        - "traefik.http.services.kambingku.loadbalancer.server.port=8501"
        - "traefik.http.services.kambingku.loadbalancer.sticky.cookie=true"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
